kind: Service
apiVersion: v1
metadata:
  name: sftp
  namespace: sftp
  labels:
    environment: production
spec:
  type: "NodePort"
  ports:
  - name: "ssh"
    port: 22
    targetPort: 22
    nodePort: 30022
  selector:
    app: sftp